"""
Read-only markdown mirror of working memory (UPG-MEMORY-LEGIBLE-FILE-
PROJECTION part (a)).

The one axis a hand-written MEMORY.md beats vectr on is openability: a
teammate (or an agent without MCP tool access) can `cat`/grep/`git diff` a
plain file without knowing vectr exists. `vectr memory export` renders the
live notes in a workspace to a deterministic markdown file so that axis is
covered too — WITHOUT giving up the database as the single source of truth.

Nothing ever reads this file back. It is lossy by design: embedding vectors,
the append-only note_events history, anchor content-hashes, trigger
conditions, and provenance nuance beyond a one-word label do not round-trip
through markdown, and no code in this module (or anywhere else) parses this
file back into the store. Memory is changed through vectr_remember /
vectr_revoke / vectr_forget (or their CLI equivalents) — never by editing
this file. See docs/tasks.md's explicit non-goal: part (b), a real
check-out/check-in editor round-trip, is a separate, not-yet-built feature
with its own two-writer-race design; this module must never grow into it.

Determinism is the load-bearing design constraint. `git diff` of the
exported file is meant to read as a free audit log of what memory learned:
re-exporting with no intervening write must produce a byte-identical file,
or every export produces spurious diff noise that defeats the whole point.
That rules out anything that varies between two calls at different wall-
clock times with identical underlying data — relative ages ("3h ago"),
timestamps rendered with sub-day precision, and any note ordering derived
from set/dict iteration or accidental sort-key ties. Every render step below
uses: `note_id` ascending (never insertion time, since note_id already IS
insertion order and this makes tie-breaking explicit), `_date_str` (calendar
date only, no time-of-day) instead of `_age_str`, and a fixed kind-section
order (VALID_KINDS) instead of first-seen order.
"""
from __future__ import annotations

import logging
import os
import tempfile
import threading
from pathlib import Path
from typing import TYPE_CHECKING

from agent.config import MEMORY_EXPORT_DEBOUNCE_SECONDS
from agent.working_context_store._store import (
    _ANTI_MEMORY_TEMPLATE,
    _date_str,
    _note_title,
)
from agent.working_context_store._types import DEFAULT_KIND, VALID_KINDS

if TYPE_CHECKING:
    from agent.working_context_store._store import WorkingContextStore
    from agent.working_context_store._types import WorkingNote

_logger = logging.getLogger("vectr.memory_export")

# Marker file (mirrors the `.vectr/style` per-workspace durable-setting
# convention in app/service.py::_read_style_override) — auto-refresh is
# opt-in per workspace: the file's mere presence, holding the last export
# target path, is what tells the post-write hook to keep re-rendering. No
# env var, no daemon in-memory state, no IPC; just a shared filesystem read,
# so a CLI process and a running daemon agree without coordination.
_EXPORT_MARKER_REL = Path(".vectr") / "memory_export_path"

# Kind -> section heading label (UPG-MEMORY-LEGIBLE-FILE-PROJECTION). A
# closed protocol mapping over VALID_KINDS, not an operator-tunable weight —
# same precedent as VALID_KINDS itself and _ANTI_MEMORY_TEMPLATE living as
# plain constants beside the store rather than in config.yaml: there is
# nothing here for an operator to retune, only a fixed vocabulary to label.
_KIND_SECTION_LABELS: dict[str, str] = {
    "directive": "Directives",
    "task": "Tasks",
    "gotcha": "Gotchas",
    "finding": "Findings",
    "reference": "References",
    "decision": "Decisions",
    "operational": "Operational Notes",
}

_HEADER_COMMENT = (
    "<!-- Generated by `vectr memory export` -- read-only mirror of vectr's "
    "working memory. Nothing reads this file back: edits made here are lost "
    "on the next export. The database is the source of truth; change memory "
    "with vectr_remember / vectr_revoke / vectr_forget (or their CLI "
    "equivalents), not by editing this file. -->"
)


def _group_by_kind(notes: list["WorkingNote"]) -> list[tuple[str, list["WorkingNote"]]]:
    """Bucket notes by kind in VALID_KINDS order (note_id ascending within
    each bucket, since `notes` is already supplied in that order by
    `notes_for_export`). Any kind outside VALID_KINDS — there should never
    be one, since remember() validates against it, but a mirror must never
    crash on a row it doesn't recognize — sorts after every known kind,
    alphabetically among itself, so it still renders instead of vanishing."""
    buckets: dict[str, list["WorkingNote"]] = {}
    for note in notes:
        buckets.setdefault(note.kind or DEFAULT_KIND, []).append(note)
    ordered_kinds = [k for k in VALID_KINDS if k in buckets]
    extra_kinds = sorted(k for k in buckets if k not in VALID_KINDS)
    return [(k, buckets[k]) for k in ordered_kinds + extra_kinds]


def _resolve_note_state(
    note: "WorkingNote", state_info: dict | None,
) -> tuple[str, str | None]:
    """Mirrors `_format_full_block`'s exact state precedence (revoked wins
    over superseded, which wins over active) so the export file and the
    MCP/CLI recall surfaces never disagree about a note's lifecycle state.

    Returns (state_label, body_override). body_override is the anti-memory
    deterrent paragraph when revoked, else None (render note.content as-is).
    """
    state = (state_info or {}).get("state")
    if state == "revoked":
        revoked_date = (
            _date_str(state_info["ts"]) if state_info.get("ts") else _date_str(note.created_at)
        )
        reason = state_info.get("reason") or "no reason given"
        deterrent = _ANTI_MEMORY_TEMPLATE.format(
            created_date=_date_str(note.created_at),
            revoked_date=revoked_date,
            reason=reason,
            summary=_note_title(note),
        )
        return "revoked", deterrent

    if note.valid_until is not None:
        sup_by = note.superseded_by or (
            f"note#{note.superseded_by_note_id}" if note.superseded_by_note_id else None
        )
        if sup_by:
            sup_date = _date_str(note.superseded_at or note.valid_until)
            return f"superseded by {sup_by}, {sup_date}", None
        return "superseded", None

    # Forward-compatible fallback: a fold state this module doesn't know
    # about yet (e.g. a future "expired" lifecycle, UPG-MEMORY-DECAY) still
    # renders honestly with its own label instead of silently defaulting to
    # "active" or crashing on an unrecognized value.
    if state and state != "active":
        return state, None

    return "active", None


def _render_note_block(note: "WorkingNote", state_info: dict | None) -> str:
    """One note's markdown block: a stable `### [#N] Title` heading (the id
    anchor part (b) will need, and what makes the file diffable/greppable
    per-note) followed by a metadata bullet list and the body."""
    state_label, body_override = _resolve_note_state(note, state_info)
    title = _note_title(note)
    heading = f"### [#{note.note_id}] {title}"

    meta_lines = [
        f"- kind: {note.kind or DEFAULT_KIND}",
        f"- priority: {note.priority}",
        f"- created: {_date_str(note.created_at)}",
        f"- state: {state_label}",
    ]
    if note.tags:
        meta_lines.append(f"- tags: {', '.join(note.tags)}")
    if note.author_id:
        meta_lines.append(f"- author: {note.author_id}")
    meta_lines.append(f"- provenance: {note.provenance}")

    body = body_override if body_override is not None else note.content
    return "\n\n".join([heading, "\n".join(meta_lines), body.strip()])


def render_memory_markdown(
    notes: list["WorkingNote"], note_states: dict[int, dict],
) -> str:
    """Top-level render entry point: header comment + title + one `##`
    section per non-empty kind bucket, each holding its notes' blocks in
    note_id-ascending order. Deterministic given the same (notes,
    note_states) input — no wall-clock-dependent content anywhere."""
    parts = [_HEADER_COMMENT, "# Working Memory"]
    for kind, kind_notes in _group_by_kind(notes):
        label = _KIND_SECTION_LABELS.get(kind, kind.title())
        blocks = [_render_note_block(n, note_states.get(n.note_id)) for n in kind_notes]
        parts.append(f"## {label}\n\n" + "\n\n".join(blocks))
    return "\n\n".join(parts) + "\n"


def write_memory_markdown(path: Path, content: str) -> None:
    """Atomic write: build the file fully in a temp file beside the target,
    then os.replace() it into place, so a concurrent reader (an editor, a
    `git diff`, or the daemon's own next export) never observes a partially
    written file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=str(path.parent), prefix=".memory_export_", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, str(path))
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def export_memory(store: "WorkingContextStore", workspace: str, path: Path) -> None:
    """Render `workspace`'s notes and write them to `path`. The single
    synchronous entry point both `vectr memory export` (CLI, direct call)
    and the debounced post-write hook (`_run_export`, below) funnel through,
    so there is exactly one rendering code path to keep byte-identical."""
    notes = store.notes_for_export(workspace)
    note_states = store.note_event_states(workspace, notes)
    content = render_memory_markdown(notes, note_states)
    write_memory_markdown(path, content)


def _read_export_target(workspace_root: str) -> Path | None:
    """Read the opt-in marker file written by `vectr memory export`. Absent
    marker (the common case: auto-export was never configured for this
    workspace) means the post-write hook is a no-op — matches the
    `.vectr/style` override-file convention (`_read_style_override` in
    app/service.py) rather than inventing a new mechanism."""
    marker = Path(workspace_root) / _EXPORT_MARKER_REL
    try:
        raw = marker.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    if not raw:
        return None
    target = Path(raw)
    return target if target.is_absolute() else Path(workspace_root) / target


def write_export_target(workspace_root: str, resolved_path: Path) -> None:
    """Record `resolved_path` as this workspace's auto-refresh target so
    future writes keep the mirror current. Called by the CLI after a
    successful `vectr memory export` — the marker's presence is what turns
    on the debounced hook for subsequent remember()/revoke()/etc calls."""
    marker = Path(workspace_root) / _EXPORT_MARKER_REL
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text(str(resolved_path), encoding="utf-8")


# Debounce state: one pending threading.Timer per workspace root. A
# self-contained equivalent of agent/watcher.py's _DebounceTimer rather than
# a cross-import of it — that class lives in the code-watching concern
# domain and this is memory-export; duplicating ~10 lines here keeps the two
# concerns independently changeable.
_pending_timers: dict[str, threading.Timer] = {}
_pending_timers_lock = threading.Lock()


def _run_export(workspace: str, target: Path, store: "WorkingContextStore") -> None:
    try:
        export_memory(store, workspace, target)
    except Exception:
        _logger.warning("memory export failed for workspace %s", workspace, exc_info=True)
    finally:
        with _pending_timers_lock:
            _pending_timers.pop(workspace, None)


def schedule_export_if_configured(workspace: str, store: "WorkingContextStore") -> None:
    """Called from `_bump_notes_epoch()` after every note write
    (remember/promote/revoke/reinstate/forget) — schedules a debounced
    re-render if (and only if) this workspace has an export target
    configured. `workspace` doubles as both the store's workspace key and
    the filesystem root the `.vectr/memory_export_path` marker lives under
    (VectrService always calls store methods with `workspace=self._workspace_root`,
    so the two are already the same string at every real call site). Must
    never raise and must never block the write path: a `remember()` call
    succeeding or failing must never depend on export machinery, so every
    failure mode here is caught and logged, never propagated."""
    try:
        target = _read_export_target(workspace)
        if target is None:
            return
        with _pending_timers_lock:
            existing = _pending_timers.get(workspace)
            if existing is not None:
                existing.cancel()
            timer = threading.Timer(
                MEMORY_EXPORT_DEBOUNCE_SECONDS,
                _run_export,
                args=(workspace, target, store),
            )
            timer.daemon = True
            _pending_timers[workspace] = timer
            timer.start()
    except Exception:
        _logger.warning("failed to schedule memory export for workspace %s", workspace, exc_info=True)
