r"""
Import memory files into vectr's working-memory store (UPG-MEMORY-IMPORT).

`vectr memory export` and `vectr memory edit` are the one-way-out and
check-out/check-in paths. This module is the long-missing one-way-in: a
way to bring existing on-disk memory (a hand-written MEMORY.md, an editor's
native instruction file, an editor's native rules dir) into the store
without re-entering it by hand. The full CLI surface sits in main.py's
`cmd_memory` dispatch; this file is the pure translation layer behind it.

Design rules the module explicitly defends:

* Idempotent on content: a re-run of `vectr memory import` against an
  unchanged source file creates zero new notes. Source-line and content
  hash are recorded on the imported note's tags so a later run can find
  and skip it. The check is BY CONTENT, not by note_id, because a re-run
  has no note_ids to compare against — the import path is a one-way
  door.

* Granularity: a source file is NOT one note and NOT one note per line.
  Heading boundaries (Markdown `^#{1,6}\s+`) split it into logical
  sections, the same way a human skims a `MEMORY.md`. A heading-less file
  is one note (a heading-less file is, structurally, a single block of
  text — there is no subdivision to make). A vectr export file is
  detected by its `<!-- Generated by ... -->` header comment and parsed
  through the existing `parse_edit_buffer()` grammar, recovering each
  original block as a note with its declared kind/priority/tags/provenance
  carried forward.

* Provenance: every imported note gets `provenance="auto"` — the same
  class machine-captured facts with no reviewing judgment already carry
  (bm2-design-skeleton.md §5). A hand-written `MEMORY.md` is structurally
  indistinguishable from a generator's output to a parser, so the
  importer does not claim "human" provenance for it. The exceptions are
  narrow and structural, not semantic: a note whose body contains
  imperative-rule markers (the closed keyword set in
  `_IMPERATIVE_KEYWORDS` below) is upgraded to `provenance="agent"`,
  because classify-as-directive + classify-as-auto would be rejected at
  write time (an unreviewed standing rule is a contradiction in terms —
  see `remember()`'s `auto + directive` guard). The promotion is the
  smallest possible deviation from auto, exactly enough to satisfy the
  write-time guard, and the report names every note where it fires so
  the user can audit it.

* Dry run: `--dry-run` prints exactly what would be created (kind,
  title, source file, source-line range, provenance) and changes nothing.
  Memory is the one resource the user cannot easily reconstruct, so dry
  run is the path of first resort — see the CLI's --dry-run help text in
  main.py.

* Discovery: with no `--path`, the module walks a short, closed list of
  default candidate files at the workspace root. With `--path` repeated
  N times, the user can pass any file (or any directory, walked
  recursively for *.md/*.mdc files). The candidate list is configurable
  via `agent.config.MEMORY_IMPORT_CANDIDATE_FILES` (a list of workspace-
  relative paths), with a documented default of
  (`MEMORY.md`, `CLAUDE.md`, `AGENTS.md`, `.cursorrules`,
  `.github/copilot-instructions.md`).

The rail that this module is most careful about: NO query-side heuristics
(Rail 1 in the lane brief). The classifier below is a structural
inspection of TEXT THE USER HANDED US — the file the user pointed at. It
is not inspecting a search query. The keyword set is closed and short
(8 entries); longer lists would cross the line into "let me read the
file and tell you what it means" semantics, which is exactly the failure
the rail is built against.
"""
from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from agent.working_context_store._export import _HEADER_COMMENT as _EXPORT_HEADER_COMMENT
from agent.working_context_store._memory_edit import parse_edit_buffer
from agent.working_context_store._types import (
    DEFAULT_KIND,
    VALID_KINDS,
)

if TYPE_CHECKING:
    from agent.working_context_store._store import WorkingContextStore
    from agent.working_context_store._types import WorkingNote


# The closed, structural classification set. Short and shallow on
# purpose: a 30-keyword rule list would be "let me read the file and tell
# you what it means" semantics, which Rail 1 forbids. The 8 words below
# are the imperative-mode sentinels a human reader would also notice at a
# glance ("MUST" / "NEVER" / "DO NOT" all signal a rule, not a finding);
# the rule "any one of these in the body AND kind inference below would
# pick directive" is exactly the structural test that makes a directive-
# kinded import survivable through the auto+directive write-time guard.
#
# All keywords are uppercase to make the test stable across both
# imperative ("MUST run tests before commit") and prose ("You must run
# tests before commit") renderings, matching the casing a hand-written
# MEMORY.md typically uses for rule declarations.
_IMPERATIVE_KEYWORDS: tuple[str, ...] = (
    "MUST", "MUST NOT", "NEVER", "ALWAYS", "DO NOT", "DON'T", "REQUIRED", "FORBIDDEN",
)

# Closed list of "directive-typical" source files — the ones the brief
# describes as "holding unconditional directives" rather than "relevance-
# ranked learnings" (CLAUDE.md / .cursorrules / AGENTS.md / the editor's
# native rules file). The lane brief's exact instruction: "The source
# file is itself evidence about the kind. ... Use the file, not just the
# sentence." A heading like `# Test policy` in CLAUDE.md is a much
# stronger candidate for `kind="directive"` than the same heading in a
# hand-written `MEMORY.md`. The structural signal here is the FILE NAME
# (a closed set, not a content heuristic) — Rail 1's "structural
# inspection of text the user handed us" still applies, because the file
# name is the user's own declaration of what they wrote it for.
_DIRECTIVE_TYPICAL_FILES: frozenset[str] = frozenset({
    "CLAUDE.md", "AGENTS.md", ".cursorrules",
    ".github/copilot-instructions.md",
})


def _is_directive_typical_file(source: Path) -> bool:
    """True if `source` is one of the closed `_DIRECTIVE_TYPICAL_FILES`
    paths, matched against the POSIX form of the path. The closed set
    mixes top-level files (`CLAUDE.md`, `AGENTS.md`, `.cursorrules`)
    with one nested file (`.github/copilot-instructions.md`, which
    lives in a `.github/` subdirectory). The basename alone
    (`Path.name`) only matches top-level files, so a strict
    `source.name in _DIRECTIVE_TYPICAL_FILES` check silently misses
    the nested case — a real classifier gap, not a design call.

    The check accepts BOTH an exact POSIX match (the test's bare
    `Path(".github/copilot-instructions.md")` shape) and a
    `"/" + typical` suffix match (the real `Path(workspace /
    ".github/copilot-instructions.md")` shape, which renders to
    `/some/workspace/.github/copilot-instructions.md`). Both
    reduce to the same membership test against the same closed
    set; neither is a content heuristic and neither reads the
    file. The suffix form is anchored to `"/" + typical` so a
    path like `/foo/other-copilot-instructions.md` cannot
    false-positive."""

    posix = source.as_posix()
    for typical in _DIRECTIVE_TYPICAL_FILES:
        if posix == typical or posix.endswith("/" + typical):
            return True
    return False

# Tags we attach to every imported note to support idempotency and
# provenance display. Closed vocabulary — same category as the export
# kind-section labels in _export.py: a fixed protocol string, not
# caller-tunable.
_TAG_IMPORTED = "imported"
_TAG_SOURCE_PREFIX = "src:"           # "src:MEMORY.md" — human-readable source label
_TAG_SOURCE_HASH_PREFIX = "src-sha:"   # "src-sha:<16 hex>" — content fingerprint at import
_TAG_SOURCE_LINES_PREFIX = "src-lines:"  # "src-lines:12-34" — line range in the source file

# The minimum length of a body for the importer to consider it a note.
# Shorter blocks (a single line of text, a stray heading with no body,
# a fragment of boilerplate) are skipped with a "skipped: too short"
# report line, not silently absorbed. The 8-character floor matches
# `_note_title()`'s 80-char ceiling on the other end: a 1-character body
# carries no recoverable content anyway.
_MIN_BODY_CHARS = 8


@dataclass
class ImportCandidate:
    """One source file the importer is about to read, with the resolved
    path and the line-count the candidate scanner recorded before parsing
    (used by the report to distinguish "file not found" from "file
    empty")."""

    path: Path
    exists: bool
    size_bytes: int


@dataclass
class ParsedSection:
    """One chunk of a non-export source file: the heading line (or
    `None` for a heading-less file's single body), the heading's line
    number in the source file, and the body. Line numbers are 1-indexed
    and recorded so the report can name "lines 12-34" — the line range
    the user can jump to in their editor to verify what was imported.
    """

    heading: str | None
    body: str
    start_line: int
    end_line: int


@dataclass
class PlannedNote:
    """One note the importer is about to write. The fields are the exact
    values the eventual `store.remember()` call will use; the dry-run
    report and the actual-write report are both formatted straight off
    this shape so they cannot disagree about what a note is."""

    source_path: Path
    source_start_line: int
    source_end_line: int
    title: str
    content: str
    kind: str
    priority: str
    tags: list[str]
    provenance: str
    author_id: str = "import"


@dataclass
class ImportPlan:
    """The full output of `plan_import()`: every note the importer would
    create from every source file, plus the per-source statistics the
    report needs. `skipped_too_short` and `skipped_existing` are recorded
    separately from `planned` so a re-run's report can name what was
    found and what was reused rather than only what was new — the
    opposite of a silent no-op that would let a user think they re-
    imported when they didn't."""

    source_files: list[Path]
    planned: list[PlannedNote] = field(default_factory=list)
    skipped_too_short: list[tuple[Path, int, str]] = field(default_factory=list)  # (path, line, preview)
    skipped_existing: list[tuple[Path, int, str]] = field(default_factory=list)  # (path, line, preview)
    parse_errors: list[tuple[Path, int, str]] = field(default_factory=list)  # (path, line, reason)

    def is_empty(self) -> bool:
        return not self.planned and not self.skipped_too_short and not self.parse_errors


@dataclass
class ImportResult:
    """The actual-write output: one entry per new note written, with the
    new note_id the store assigned. Skipped counts are echoed so the CLI
    can format a one-line summary that doesn't require re-walking the
    plan."""

    written: list[tuple[PlannedNote, int]] = field(default_factory=list)  # (plan, new_note_id)
    skipped_existing: int = 0
    skipped_too_short: int = 0
    parse_errors: int = 0


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def _resolve_candidate_files(
    workspace: Path, extra_paths: list[Path] | None,
) -> list[ImportCandidate]:
    """Build the ordered list of source files the importer will try to
    read: every entry in `extra_paths` (user-supplied) first, in the
    order given, then the configured default candidate list (every file
    that actually exists on disk; missing ones are reported as
    `exists=False` but never raised on — a missing default file is the
    common case for a workspace that has never used that filename)."""

    # Read the configured candidate list at call time so a test that
    # monkeypatches MEMORY_IMPORT_CANDIDATE_FILES sees the override.
    from agent.config import MEMORY_IMPORT_CANDIDATE_FILES

    candidates: list[ImportCandidate] = []
    for p in extra_paths or []:
        resolved = p if p.is_absolute() else workspace / p
        try:
            size = resolved.stat().st_size if resolved.exists() else 0
        except OSError:
            size = 0
        candidates.append(ImportCandidate(path=resolved, exists=resolved.exists(), size_bytes=size))
    for rel in MEMORY_IMPORT_CANDIDATE_FILES:
        resolved = workspace / rel
        try:
            size = resolved.stat().st_size if resolved.exists() else 0
        except OSError:
            size = 0
        candidates.append(ImportCandidate(path=resolved, exists=resolved.exists(), size_bytes=size))
    return candidates


def _walk_directory_for_markdown(directory: Path) -> list[Path]:
    """Recursive walk of a user-supplied directory, returning every
    .md / .mdc file. Capped at a sensible depth (8) so a runaway
    walk against `node_modules` or `.git` doesn't burn minutes. The
    caller is responsible for putting the directory under the
    workspace; this function trusts its input."""

    out: list[Path] = []
    if not directory.exists() or not directory.is_dir():
        return out
    for path in directory.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in (".md", ".mdc"):
            continue
        # Cheap depth cap by counting separators in the relative part.
        try:
            rel = path.relative_to(directory)
        except ValueError:
            continue
        depth = len(rel.parts) - 1
        if depth > 8:
            continue
        out.append(path)
    return sorted(out)


# ---------------------------------------------------------------------------
# Source-file classification: is this a vectr export?
# ---------------------------------------------------------------------------

def _is_export_file(head_text: str) -> bool:
    """True if the file's first ~512 bytes contain the exact
    `_EXPORT_HEADER_COMMENT` sentinel that `render_memory_markdown()`
    always emits as its first line. The sentinel is the same constant
    `_export.py` writes, so a round-trip detection is exact and
    structural (no heuristic, no tail-match on `Working Memory`) —
    a hand-written `MEMORY.md` that happens to contain the words
    "Working Memory" is NOT misclassified as an export."""

    if not head_text:
        return False
    return _EXPORT_HEADER_COMMENT in head_text[:2048]


# ---------------------------------------------------------------------------
# Parsing: non-export files
# ---------------------------------------------------------------------------

# A heading line: starts with 1-6 `#` characters, then a space, then any
# text. Compiled once at module load. Matches the standard CommonMark
# ATX-heading shape a hand-written MEMORY.md uses.
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def _split_into_sections(text: str) -> list[ParsedSection]:
    """Walk a non-export source file and split it into one
    `ParsedSection` per heading boundary. Sections are 1-indexed by
    their start line; the section's body is everything from the line
    AFTER the heading up to (but not including) the next heading or end
    of file. Headings are stripped from the body — the heading text is
    recorded separately on the section, and re-attaches to the note's
    title in the planned-note shape.

    A file with no headings at all produces one section whose
    `heading` is None and whose body is the whole file. The whole-file
    case is the only one where the granularity choice is forced (no
    boundaries exist), and a "one section per file" outcome is the
    only honest reading.

    Headings inside fenced code blocks are NOT section boundaries —
    the regex matches them, but we walk the file line by line and
    skip the heading-match step while inside a code fence. A heading
    inside a comment-quoted HTML block is the same: a `<!-- ... -->`
    block is treated as code-shaped for this purpose."""

    sections: list[ParsedSection] = []
    lines = text.splitlines()
    if not lines:
        return sections

    in_fence = False
    fence_marker: str | None = None
    in_comment = False
    i = 0
    n = len(lines)
    current_heading: str | None = None
    current_start: int = 1
    body_lines: list[str] = []

    def _flush(end_line: int) -> None:
        body = "\n".join(body_lines).strip()
        if body or current_heading is not None:
            sections.append(ParsedSection(
                heading=current_heading,
                body=body,
                start_line=current_start,
                end_line=end_line,
            ))

    while i < n:
        line = lines[i]
        stripped = line.lstrip()
        # Track fenced code blocks. We deliberately support the
        # CommonMark shape of "at least 3 backticks OR 3 tildes, on a
        # line by themselves or with an info string". An opening fence
        # closes on the next line with the same or longer marker.
        if not in_comment:
            fence_match = re.match(r"^(`{3,}|~{3,})", stripped)
            if fence_match:
                marker = fence_match.group(1)
                if not in_fence:
                    in_fence = True
                    fence_marker = marker[0]  # only the leading char matters for closure
                elif marker[0] == fence_marker and len(marker) >= len(fence_marker):
                    in_fence = False
                    fence_marker = None
                body_lines.append(line)
                i += 1
                continue
        # Track HTML comment blocks. A `<!--` starts one; a `-->` ends
        # one. The export-file header is exactly such a block, and we
        # want to NOT see it as a section boundary either.
        if not in_fence:
            if not in_comment and "<!--" in line:
                in_comment = True
            if in_comment:
                body_lines.append(line)
                if "-->" in line:
                    in_comment = False
                i += 1
                continue
        if not in_fence and not in_comment:
            heading_match = _HEADING_RE.match(line)
            if heading_match:
                # Flush the current section (if any) before opening the new one.
                _flush(i)  # end_line of prior section = line just before this heading (i, 0-indexed in splitlines)
                current_heading = heading_match.group(2).strip()
                current_start = i + 1  # 1-indexed
                body_lines = []
                i += 1
                continue
        body_lines.append(line)
        i += 1

    _flush(n)  # close the last section
    # A trailing-empty-body section is only created if it had a heading;
    # the closing call's `if body or current_heading is not None` handles
    # that. Strip the leading `<!-- ... -->` HTML comment block from the
    # first section's body if it sits there alone (a file whose first
    # thing is the export header is a different code path entirely —
    # this branch is the non-export path, so the comment is just noise).
    return sections


# ---------------------------------------------------------------------------
# Per-section classification and shaping
# ---------------------------------------------------------------------------

def _content_hash(text: str) -> str:
    """sha256[:16] of `text` — the same fingerprint shape the store
    uses for code-hash staleness checks. Stable across calls and runs;
    identical inputs always give the same tag suffix."""

    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _infer_kind_and_provenance(
    section: ParsedSection, source: Path | None = None,
) -> tuple[str, str, str]:
    """Classify one parsed section into `(kind, priority, provenance)`.

    The rule, in order:

    1. If the heading starts with an imperative-mode word from
       `_IMPERATIVE_KEYWORDS` (case-insensitive) AND the body is short
       enough to be a single rule (≤ 3 lines of substantive content),
       classify as `kind="directive"`. A directive with a long body is
       almost always a doc-block, not a rule, and the boundary here
       matters: a 200-line block under "MUST" is documentation, not a
       rule, and forcing it to directive would put it in Tier 0
       injection — wrong.

    2. Otherwise, if the SOURCE FILE is in the closed
       `_DIRECTIVE_TYPICAL_FILES` set (CLAUDE.md / AGENTS.md /
       .cursorrules / the editor's instruction file) AND the body is
       short, classify as `kind="directive"`. This is the lane
       brief's "the source file is itself evidence about the kind"
       rule: a heading like `# Test policy` in CLAUDE.md is a much
       stronger candidate for `directive` than the same heading in a
       hand-written `MEMORY.md`. The signal here is the FILE NAME
       (a closed set, not a content heuristic). A long body in a
       directive-typical file still falls back to `finding` (a 200-
       line block under any heading is documentation, not a rule).

    3. Otherwise, classify as `kind="finding"`. The `finding` kind is
       the DEFAULT_KIND and the right home for anything that is not
       a short imperative rule. This is the deliberate "prefer the
       weaker claim" stance the lane brief calls out: a finding that
       should have been a directive merely ranks lower, but a
       directive that should have been a finding gets obeyed
       unconditionally forever.

    4. Provenance: if kind is directive, upgrade from `auto` to
       `agent` so the note survives the `auto + directive` write-time
       guard (see `_store.remember()`). For finding, keep `auto` —
       that's the imported class, and the user can promote a finding
       to agent later via `vectr_promote` or to human via edit.

    5. Priority: rules get `high`; findings get `medium`. A rule that
       carries `kind=directive` but `priority=low` would still be
       Tier 0-injected (kind, not priority, gates that), but a `high`
       priority signals to a reader that the note is meant to be
       acted on, not just stored.
    """

    heading = (section.heading or "").strip()
    body = section.body.strip()
    substantive_lines = [ln for ln in body.splitlines() if ln.strip()]
    short_enough_to_be_a_rule = 0 < len(substantive_lines) <= 3

    heading_first_word = heading.split(maxsplit=1)[0].upper() if heading else ""
    is_imperative_heading = heading_first_word in _IMPERATIVE_KEYWORDS

    is_directive_typical_file = (
        source is not None and _is_directive_typical_file(source)
    )

    if is_imperative_heading and short_enough_to_be_a_rule:
        return "directive", "high", "agent"
    if is_imperative_heading:
        # Long body under an imperative heading: still note that it was
        # declared as a rule, but classify as `finding` so a 200-line
        # doc-block is not Tier 0-injected. The report flags this
        # promotion-via-headword so the user can audit it.
        return "finding", "medium", "auto"
    if is_directive_typical_file and short_enough_to_be_a_rule:
        # The source file is a known rule-bearing instruction file
        # (CLAUDE.md, AGENTS.md, .cursorrules, or a GitHub Copilot
        # instructions file) and the section is short enough to be a
        # rule. Classify as `directive` so the section is Tier 0-
        # injected, matching the way a hand-written `CLAUDE.md` is
        # typically read (the user expects every short section to be
        # a rule, not a learning).
        return "directive", "high", "agent"
    return DEFAULT_KIND, "medium", "auto"


def _make_title(section: ParsedSection) -> str:
    """The title we will store on the new note. Heading if present,
    otherwise the first non-empty body line truncated to 80 chars
    (same shape `_note_title()` already uses for its fallback, kept
    consistent so a re-exported import reads the same as a hand-
    written note)."""

    if section.heading:
        return section.heading[:80]
    first = next((ln.strip() for ln in section.body.splitlines() if ln.strip()), "(no title)")
    return first[:80]


def _build_tags_for_planned(
    source: Path, section: ParsedSection, body_text: str,
) -> list[str]:
    """Tags attached to a single planned note. The `imported` tag is
    the at-read-time signal: a recall that lists a note carrying
    `imported` is telling the user "this came from a file, not from
    this session's observations". The `src:` / `src-sha:` / `src-lines:`
    tags are the at-trace-time signal: a user who wants to know "where
    did this come from?" finds the answer on the note itself, no
    separate lookup required (matches the same load-bearing principle
    the store's anchor-hash design holds to — proof at read time,
    not via a separate audit log).

    Tag list is sorted for determinism; the store dedupes on
    insertion, but sorted order means two `set(tags)`-style tests
    agree."""

    rel_source = source.name  # basename only — the workspace-relative
    # path would leak the user's full filesystem layout into a tag,
    # which the store then echoes at every recall. Basename is enough
    # to identify the file in context.
    return sorted([
        _TAG_IMPORTED,
        f"{_TAG_SOURCE_PREFIX}{rel_source}",
        f"{_TAG_SOURCE_HASH_PREFIX}{_content_hash(body_text)}",
        f"{_TAG_SOURCE_LINES_PREFIX}{section.start_line}-{section.end_line}",
    ])


# ---------------------------------------------------------------------------
# Parsing: export files
# ---------------------------------------------------------------------------

def _parse_export_file(text: str, source: Path) -> tuple[list[PlannedNote], list[tuple[Path, int, str]]]:
    """Parse a vectr export file (`render_memory_markdown()` output)
    into a list of `PlannedNote` objects. Reuses `parse_edit_buffer()`
    rather than re-deriving the block grammar — the export is the
    SAME buffer grammar `vectr memory edit` consumes, so the parser
    is the parser.

    Each parsed block has its `kind`, `priority`, `tags`, `provenance`,
    and (if present) `author_id` carried forward from the rendered
    metadata bullets, then turned into a `remember()` call that
    re-creates the original note. The block's `[#N]` heading anchor
    is NOT preserved (a re-import has no guarantee the original
    note_id is still free — and the note_id is purely the database's
    primary key, not a semantic identifier).

    A parsed block whose body is empty after `parse_edit_buffer()` is
    dropped with a parse_error row: it means a corrupt block boundary
    in the export, which the export's own determinism contract says
    cannot happen but a hand-edited file could still produce.
    """

    planned: list[PlannedNote] = []
    errors: list[tuple[Path, int, str]] = []
    try:
        blocks = parse_edit_buffer(text)
    except Exception as exc:  # parse_edit_buffer raises MemoryEditParseError
        errors.append((source, 1, f"could not parse export file: {exc}"))
        return planned, errors

    # The export header comment line is the first line of `text`. We
    # track the per-block start_line by counting the `# ` boundaries
    # encountered before each `### ` block, since the export grammar
    # uses both `##` (kind section) and `###` (note heading).
    boundary_pattern = re.compile(r"^(#{2,3}) .+$", re.MULTILINE)
    block_starts: list[int] = []
    for m in boundary_pattern.finditer(text):
        marker = m.group(1)
        if marker == "###":
            block_starts.append(text[: m.start()].count("\n") + 1)
    block_iter = iter(block_starts)

    for block in blocks:
        # `block.note_id is None` means a `### Title` block with no
        # `[#N]` anchor — not a valid export shape (the export grammar
        # always emits an anchor). We skip these with a parse_error
        # rather than treating them as fresh notes: an export file
        # with anchor-less blocks is either hand-edited or corrupt,
        # and a user who wants to import a non-export file would
        # point at a non-export file.
        if block.note_id is None:
            errors.append((source, 0, "export block missing [#N] anchor; not a valid vectr export"))
            continue
        body = block.body.strip()
        if not body:
            errors.append((source, 0, f"export block #{block.note_id} has empty body"))
            continue
        # Pull structured fields out of the metadata bullets `parse_
        # edit_buffer()` already extracted. `kind` falls back to
        # DEFAULT_KIND when missing, same as the store. `provenance`
        # falls back to "agent" (the historic default; an export
        # written before this import path existed would have had
        # "agent" as its default class, and the round-trip should
        # preserve that class so a re-imported file reads as "agent"
        # not "auto").
        meta_kind = block.meta.get("kind") or DEFAULT_KIND
        if meta_kind not in VALID_KINDS:
            meta_kind = DEFAULT_KIND
        meta_priority = block.meta.get("priority") or "medium"
        meta_provenance = block.meta.get("provenance") or "agent"
        meta_tags = [t.strip() for t in (block.meta.get("tags") or "").split(",") if t.strip()]
        meta_author = block.meta.get("author") or ""
        title = block.title or "(no title)"
        start_line = next(block_iter, 0)
        # Carry the `imported` / `src:` / `src-sha:` tags forward. The
        # `src-sha:` tag is the same `_content_hash(body)` the idempotency
        # check below computes — including it here makes a re-import of
        # the SAME export file a no-op (the import's body, after
        # `body.strip()`, is byte-identical to the original's stored
        # body, since `render_memory_markdown()` also strips before
        # rendering). Without this tag, idempotency would only fire on
        # the non-export path, and re-importing a `vectr memory export`
        # file would create a duplicate set of notes.
        new_tags = sorted(set(meta_tags + [
            _TAG_IMPORTED,
            f"{_TAG_SOURCE_PREFIX}{source.name}",
            f"{_TAG_SOURCE_HASH_PREFIX}{_content_hash(body)}",
        ]))
        planned.append(PlannedNote(
            source_path=source,
            source_start_line=start_line,
            source_end_line=start_line,  # exact end not recoverable from
            # `parse_edit_buffer()` without a re-walk; the round-trip
            # report says "block at line N" which is enough for the
            # user to jump to the file in their editor.
            title=title,
            content=body,
            kind=meta_kind,
            priority=meta_priority,
            tags=new_tags,
            provenance=meta_provenance,
            author_id=meta_author or "import",
        ))
    return planned, errors


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------

def _is_already_imported(
    store: "WorkingContextStore", workspace: str, source: Path, body_text: str,
) -> bool:
    """Idempotency check: is there a note in this workspace whose
    `tags` already contains BOTH `src:<source.name>` AND
    `src-sha:<_content_hash(body_text)>`? Both must match — the
    `src:` tag alone matches every note from the same file (so
    re-imports of the same file would all be skipped), the
    `src-sha:` alone matches notes from different files that
    happen to share content (a contrived case, but a real
    false-positive for a moved file). The AND is the right
    granularity.

    Uses `notes_for_export()` (every note, no recall filtering)
    rather than `recall()` so superseded / revoked / expired notes
    also count: a re-import against a file the user previously
    imported and then revoked MUST still skip, not silently create
    a duplicate alongside the revoked original. The export path's
    broader scope matches what we are checking against (we are
    asking "is this import a no-op", not "would recall return
    this")."""

    expected_src = f"{_TAG_SOURCE_PREFIX}{source.name}"
    expected_sha = f"{_TAG_SOURCE_HASH_PREFIX}{_content_hash(body_text)}"
    for note in store.notes_for_export(workspace):
        tag_set = set(note.tags or [])
        if expected_src in tag_set and expected_sha in tag_set:
            return True
    return False


# ---------------------------------------------------------------------------
# Plan
# ---------------------------------------------------------------------------

def plan_import(
    workspace: Path,
    extra_paths: list[Path] | None,
    store: "WorkingContextStore" | None,
) -> ImportPlan:
    """Build the full import plan: discover candidates, parse each
    file, classify each section, check idempotency, and produce the
    ordered list of `PlannedNote` objects the CLI will either print
    (dry run) or pass to `execute_import()`.

    A `store` argument is required for the idempotency check (we
    must ask the store "is this body already imported?"). A None
    store is allowed only for the no-store dry-run case, where the
    plan is rendered as if every section were new — the dry-run
    output is then "what would be created from scratch", which is
    exactly what a first-time user wants to see.
    """

    workspace = workspace.resolve()
    candidates = _resolve_candidate_files(workspace, extra_paths)
    plan = ImportPlan(source_files=[c.path for c in candidates if c.exists])

    for cand in candidates:
        if not cand.exists or cand.size_bytes == 0:
            continue
        try:
            text = cand.path.read_text(encoding="utf-8")
        except OSError as exc:
            plan.parse_errors.append((cand.path, 0, f"could not read: {exc}"))
            continue
        if not text.strip():
            continue

        # Head text for the export-detect path: the first 2KB is
        # enough to cover `_HEADER_COMMENT` plus the leading kind
        # section headings on any realistic export.
        head_text = text[:2048]
        if _is_export_file(head_text):
            planned, errors = _parse_export_file(text, cand.path)
            # Same idempotency contract as the foreign-file path: a
            # re-import of an unchanged export file plans zero new
            # notes. `_parse_export_file()` already attaches
            # `src-sha:H(body)` to every planned block (so the
            # re-import's body, after the round-trip strip(), hashes
            # to the same tag as the original write), and the same
            # `_is_already_imported()` check the foreign path uses
            # is the one that fires here. Without this branch a
            # second `vectr memory import` against the same
            # `MEMORY.md` would duplicate the entire store.
            if store is not None:
                for note in planned:
                    if _is_already_imported(
                        store, str(workspace), note.source_path, note.content,
                    ):
                        preview = note.content[:40].replace("\n", " ")
                        plan.skipped_existing.append((
                            note.source_path, note.source_start_line, preview,
                        ))
                        continue
                    plan.planned.append(note)
            else:
                plan.planned.extend(planned)
            plan.parse_errors.extend(errors)
            continue

        # Non-export path: split into sections, classify, check
        # idempotency.
        sections = _split_into_sections(text)
        for section in sections:
            body = section.body.strip()
            if len(body) < _MIN_BODY_CHARS:
                preview = body[:40].replace("\n", " ")
                plan.skipped_too_short.append((cand.path, section.start_line, preview))
                continue
            kind, priority, provenance = _infer_kind_and_provenance(section, cand.path)
            title = _make_title(section)
            tags = _build_tags_for_planned(cand.path, section, body)
            if store is not None and _is_already_imported(store, str(workspace), cand.path, body):
                preview = body[:40].replace("\n", " ")
                plan.skipped_existing.append((cand.path, section.start_line, preview))
                continue
            plan.planned.append(PlannedNote(
                source_path=cand.path,
                source_start_line=section.start_line,
                source_end_line=section.end_line,
                title=title,
                content=body,
                kind=kind,
                priority=priority,
                tags=tags,
                provenance=provenance,
            ))
    return plan


# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------

def execute_import(
    store: "WorkingContextStore",
    workspace: str,
    plan: ImportPlan,
) -> ImportResult:
    """Write the planned notes to the store. One `remember()` call
    per planned note, in plan order (which is the same order
    `plan_import()` produced them — section order within each file,
    file order across files). Each call goes through the store's
    normal write path, so the usual write-time guards (auto+directive
    rejection, user_quote binding, scope default resolution, anchor
    hashing) all run exactly as they would for a normal `remember()`
    call. The only difference is the imported tags we attach, which
    carry forward the `imported` / `src:` / `src-sha:` / `src-lines:`
    markers so a future re-import can find and skip them.

    A single failed `remember()` does NOT abort the whole import:
    one bad line in a 200-line file should not lose the other 199.
    Failures are caught, logged via the `note_import_skipped` audit
    shape (the store's own audit mechanism, see
    `agent.working_context_store._audit.py`), and execution continues
    with the next planned note. The CLI summary names every failure
    so the user can fix the file and re-run."""

    result = ImportResult(
        skipped_existing=len(plan.skipped_existing),
        skipped_too_short=len(plan.skipped_too_short),
        parse_errors=len(plan.parse_errors),
    )
    for note in plan.planned:
        try:
            new_id = store.remember(
                workspace,
                note.content,
                tags=note.tags,
                priority=note.priority,
                kind=note.kind,
                title=note.title,
                provenance=note.provenance,
                author_id=note.author_id,
            )
        except ValueError as exc:
            # Most likely cause: an auto+directive that survived the
            # `auto + directive` write-time guard (should be impossible
            # because `_infer_kind_and_provenance` already promotes
            # directives to `agent`, but defensible code is better
            # than code that crashes on a corner case). Log and
            # continue.
            from agent.working_context_store._audit import audit
            audit(
                "NOTE_IMPORT_FAILED", workspace=workspace, source=str(note.source_path),
                title=note.title, error=str(exc),
            )
            result.parse_errors += 1
            continue
        result.written.append((note, new_id))
    return result
